server:
  port: 8080

spring:
  application:
    name: sca-k8s-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: 'nacos'
        password: 'nacos'

grpc:
  client:
    sca-k8s-provider:
      address: 'discovery:///sca-k8s-provider'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
