server:
  port: 8080

spring:
  application:
    name: sca-k8s-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: 'nacos'
        password: 'nacos'

management:
  server:
    port: 30002
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health

grpc:
  client:
    sca-k8s-provider:
      address: 'discovery:///sca-k8s-provider'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
