// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sca-k8s.proto

package com.alibaba.cloud.grpc.lib;

public interface RequestBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string consumer = 1;</code>
   * @return The consumer.
   */
  java.lang.String getConsumer();
  /**
   * <code>string consumer = 1;</code>
   * @return The bytes for consumer.
   */
  com.google.protobuf.ByteString
      getConsumerBytes();
}
