// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sca-k8s.proto

package com.alibaba.cloud.grpc.lib;

public interface ResponseBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
