// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sca-k8s.proto

package com.alibaba.cloud.grpc.lib;

public final class ScaK8sProto {
  private ScaK8sProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsca-k8s.proto\"\037\n\014ResponseBody\022\017\n\007messa" +
      "ge\030\001 \001(\t\"\037\n\013RequestBody\022\020\n\010consumer\030\001 \001(" +
      "\t2h\n\016SCAk8sProvider\022*\n\tproviderA\022\014.Reque" +
      "stBody\032\r.ResponseBody\"\000\022*\n\tproviderB\022\014.R" +
      "equestBody\032\r.ResponseBody\"\000B+\n\032com.aliba" +
      "ba.cloud.grpc.libB\013ScaK8sProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ResponseBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResponseBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseBody_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_RequestBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RequestBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestBody_descriptor,
        new java.lang.String[] { "Consumer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
