server:
  port: 8080

spring:
  application:
    name: sca-k8s-provider

management:
  server:
    port: 30001
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
