spring:
  application:
    name: sca-k8s-provider

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: 'nacos'
        password: 'nacos'

grpc:
  server:
    port: 9000

server:
  port: 8082
