server:
  port: 8080

spring:
  application:
    name: istio-sca-demo-application

management:
  server:
    port: 30001
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
